[project]
name = "sulib"
version = "0.1.0"
license-files = ["LICENSE"]
description = "Python code for SU-decomposition"
requires-python = ">=3.10"

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["error"]
